import {
  User,
  Prescription,
  VerificationRecord,
  AuditLogEntry,
  ActiveSession,
  NotificationItem,
  OverrideRequest,
  TeamMemberStats,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-001',
    organizationId: 'ABC Pharmacy - Central Hospital',
    staffId: 'PH-1025',
    name: 'Sagar Patel',
    email: 'sagar.patel@abcpharmacy.org',
    role: 'PHARMACIST',
    status: 'ACTIVE',
    department: 'Central Inpatient Pharmacy',
    initials: 'SP',
    title: 'Senior Clinical Pharmacist (RPh)',
    phone: '+1 (555) 234-8901',
    lastLogin: '2026-10-03T08:30:00Z',
  },
  {
    id: 'user-002',
    organizationId: 'ABC Pharmacy - Central Hospital',
    staffId: 'SUP-108',
    name: 'Dr. Marcus Vance',
    email: 'm.vance@abcpharmacy.org',
    role: 'SUPERVISOR',
    status: 'ACTIVE',
    department: 'Clinical Pharmacy Supervision',
    initials: 'MV',
    title: 'Pharmacy Operations Supervisor (PharmD)',
    phone: '+1 (555) 234-8902',
    lastLogin: '2026-10-03T07:15:00Z',
  },
  {
    id: 'user-003',
    organizationId: 'ABC Pharmacy - Central Hospital',
    staffId: 'ADM-001',
    name: 'Elena Rostova',
    email: 'admin@abcpharmacy.org',
    role: 'ADMIN',
    status: 'ACTIVE',
    department: 'Pharmacy Informatics & Compliance',
    initials: 'ER',
    title: 'Chief Pharmacy Systems Administrator',
    phone: '+1 (555) 234-8900',
    lastLogin: '2026-10-02T16:00:00Z',
  },
  {
    id: 'user-004',
    organizationId: 'ABC Pharmacy - Central Hospital',
    staffId: 'PH-1040',
    name: 'Rahul Sharma',
    email: 'r.sharma@abcpharmacy.org',
    role: 'PHARMACIST',
    status: 'ACTIVE',
    department: 'Outpatient Dispensing Wing',
    initials: 'RS',
    title: 'Staff Dispensing Pharmacist',
    phone: '+1 (555) 234-8904',
    lastLogin: '2026-10-03T07:45:00Z',
  },
  {
    id: 'user-005',
    organizationId: 'ABC Pharmacy - Central Hospital',
    staffId: 'SUP-112',
    name: 'Priya Shah',
    email: 'p.shah@abcpharmacy.org',
    role: 'SUPERVISOR',
    status: 'ACTIVE',
    department: 'Quality & Clinical Safety',
    initials: 'PS',
    title: 'Clinical Safety Specialist (PharmD)',
    phone: '+1 (555) 234-8905',
    lastLogin: '2026-10-03T06:50:00Z',
  },
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-1025',
    prescriptionNumber: '1025',
    hospitalId: 'ABC Pharmacy - Central Hospital',
    patientRef: 'PT-88219 (Bed 302-B, Ward 3)',
    prescriberName: 'Dr. Robert Chen, MD',
    prescriberRegNo: 'MD-55421',
    prescriptionDate: '2026-10-03',
    status: 'ACTIVE',
    sourceType: 'CAMERA_SCAN',
    createdAt: '2026-10-03T08:15:00Z',
    createdBy: 'PH-1025',
    confirmedAt: '2026-10-03T08:18:00Z',
    confirmedBy: 'PH-1025',
    medicines: [
      {
        id: 'pm-101',
        prescriptionId: 'rx-1025',
        medicineName: 'Paracetamol',
        strength: '500 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet (500mg)',
        frequency: 'TID (Every 8 hours)',
        route: 'Oral',
        duration: '3 days',
        quantity: 9,
        confirmationStatus: 'VERIFIED',
        verifiedAt: '2026-10-03T08:22:10Z',
        verifiedBy: 'Sagar Patel (PH-1025)',
        scannedMedicineId: 'med-001',
        scannedBarcode: '8901112223334',
      },
      {
        id: 'pm-102',
        prescriptionId: 'rx-1025',
        medicineName: 'Amoxicillin',
        strength: '500 mg',
        dosageForm: 'Capsule',
        dose: '1 capsule (500mg)',
        frequency: 'TID (Every 8 hours)',
        route: 'Oral',
        duration: '5 days',
        quantity: 15,
        confirmationStatus: 'VERIFIED',
        verifiedAt: '2026-10-03T08:24:45Z',
        verifiedBy: 'Sagar Patel (PH-1025)',
        scannedMedicineId: 'med-004',
        scannedBarcode: '8902223334441',
      },
      {
        id: 'pm-103',
        prescriptionId: 'rx-1025',
        medicineName: 'Pantoprazole',
        strength: '40 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet (40mg)',
        frequency: 'OD (Once daily before breakfast)',
        route: 'Oral',
        duration: '7 days',
        quantity: 7,
        confirmationStatus: 'PENDING',
      },
    ],
  },
  {
    id: 'rx-1024',
    prescriptionNumber: '1024',
    hospitalId: 'ABC Pharmacy - Central Hospital',
    patientRef: 'PT-77109 (Day Surgery, Room 4)',
    prescriberName: 'Dr. Anita Desai, MD',
    prescriberRegNo: 'MD-88120',
    prescriptionDate: '2026-10-03',
    status: 'COMPLETED',
    sourceType: 'CAMERA_SCAN',
    createdAt: '2026-10-03T07:10:00Z',
    createdBy: 'PH-1040',
    confirmedAt: '2026-10-03T07:14:00Z',
    confirmedBy: 'PH-1040',
    completedAt: '2026-10-03T07:25:00Z',
    medicines: [
      {
        id: 'pm-201',
        prescriptionId: 'rx-1024',
        medicineName: 'Azithromycin',
        strength: '500 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet',
        frequency: 'OD',
        route: 'Oral',
        duration: '3 days',
        quantity: 3,
        confirmationStatus: 'VERIFIED',
        verifiedAt: '2026-10-03T07:20:00Z',
        verifiedBy: 'Rahul Sharma (PH-1040)',
        scannedMedicineId: 'med-010',
        scannedBarcode: '8908889990001',
      },
      {
        id: 'pm-202',
        prescriptionId: 'rx-1024',
        medicineName: 'Paracetamol',
        strength: '500 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet',
        frequency: 'TID',
        route: 'Oral',
        duration: '3 days',
        quantity: 9,
        confirmationStatus: 'VERIFIED',
        verifiedAt: '2026-10-03T07:22:00Z',
        verifiedBy: 'Rahul Sharma (PH-1040)',
        scannedMedicineId: 'med-001',
        scannedBarcode: '8901112223334',
      },
    ],
  },
  {
    id: 'rx-1026',
    prescriptionNumber: '1026',
    hospitalId: 'ABC Pharmacy - Central Hospital',
    patientRef: 'PT-91402 (Cardiology OPD)',
    prescriberName: 'Dr. Marcus Vance, MD',
    prescriberRegNo: 'MD-11942',
    prescriptionDate: '2026-10-03',
    status: 'PENDING_REVIEW',
    sourceType: 'FILE_UPLOAD',
    createdAt: '2026-10-03T08:40:00Z',
    createdBy: 'PH-1025',
    ocrConfidence: 0.94,
    medicines: [
      {
        id: 'pm-301',
        prescriptionId: 'rx-1026',
        medicineName: 'Metformin',
        strength: '500 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet',
        frequency: 'BD with meals',
        route: 'Oral',
        duration: '30 days',
        quantity: 60,
        confirmationStatus: 'PENDING',
      },
      {
        id: 'pm-302',
        prescriptionId: 'rx-1026',
        medicineName: 'Atorvastatin',
        strength: '20 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet',
        frequency: 'OD at bedtime',
        route: 'Oral',
        duration: '30 days',
        quantity: 30,
        confirmationStatus: 'PENDING',
      },
    ],
  },
];

export const INITIAL_VERIFICATION_HISTORY: VerificationRecord[] = [
  {
    id: 'vr-101',
    prescriptionId: 'rx-1025',
    prescriptionNumber: '1025',
    prescriptionMedicineId: 'pm-101',
    expectedMedicineName: 'Paracetamol',
    expectedStrength: '500 mg',
    expectedDosageForm: 'Tablet',
    scannedBarcode: '8901112223334',
    scannedMedicineName: 'Paracetamol',
    scannedStrength: '500 mg',
    scannedDosageForm: 'Tablet',
    scannedManufacturer: 'GSK Healthcare Ltd',
    scannedBatchNumber: 'CAL-2608B',
    scannedExpiryDate: '12/2028',
    matchResult: { name: true, strength: true, dosageForm: true, expiryValid: true, allMatch: true },
    status: 'VERIFIED',
    rescanCount: 0,
    isRescannedAfterMismatch: false,
    staffId: 'PH-1025',
    staffName: 'Sagar Patel',
    timestamp: '2026-10-03T08:22:10Z',
  },
  {
    id: 'vr-102',
    prescriptionId: 'rx-1025',
    prescriptionNumber: '1025',
    prescriptionMedicineId: 'pm-102',
    expectedMedicineName: 'Amoxicillin',
    expectedStrength: '500 mg',
    expectedDosageForm: 'Capsule',
    scannedBarcode: '8902223334441',
    scannedMedicineName: 'Amoxicillin',
    scannedStrength: '500 mg',
    scannedDosageForm: 'Capsule',
    scannedManufacturer: 'Sun Pharma Industries Ltd',
    scannedBatchNumber: 'MOX-2609X',
    scannedExpiryDate: '03/2028',
    matchResult: { name: true, strength: true, dosageForm: true, expiryValid: true, allMatch: true },
    status: 'VERIFIED',
    rescanCount: 0,
    isRescannedAfterMismatch: false,
    staffId: 'PH-1025',
    staffName: 'Sagar Patel',
    timestamp: '2026-10-03T08:24:45Z',
  },
  {
    id: 'vr-103',
    prescriptionId: 'rx-1023',
    prescriptionNumber: '1023',
    prescriptionMedicineId: 'pm-088',
    expectedMedicineName: 'Pantoprazole',
    expectedStrength: '40 mg',
    expectedDosageForm: 'Tablet',
    scannedBarcode: '8901112223335',
    scannedMedicineName: 'Paracetamol',
    scannedStrength: '650 mg',
    scannedDosageForm: 'Tablet',
    scannedManufacturer: 'Micro Labs Ltd',
    scannedBatchNumber: 'DLO-2611A',
    scannedExpiryDate: '01/2029',
    matchResult: { name: false, strength: false, dosageForm: true, expiryValid: true, allMatch: false },
    status: 'MISMATCH',
    rescanCount: 1,
    isRescannedAfterMismatch: false,
    staffId: 'PH-1025',
    staffName: 'Sagar Patel',
    timestamp: '2026-10-03T06:55:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-001',
    timestamp: '2026-10-03T08:30:00Z',
    staffId: 'PH-1025',
    staffName: 'Sagar Patel',
    role: 'PHARMACIST',
    action: 'LOGIN',
    entityType: 'SECURITY',
    entityId: 'PH-1025',
    details: 'Staff member Sagar Patel signed in on Handheld Android Terminal.',
  },
  {
    id: 'log-002',
    timestamp: '2026-10-03T08:18:00Z',
    staffId: 'PH-1025',
    staffName: 'Sagar Patel',
    role: 'PHARMACIST',
    action: 'PRESCRIPTION_CONFIRMED',
    entityType: 'PRESCRIPTION',
    entityId: 'rx-1025',
    details: 'Confirmed OCR extracted line items for Prescription #1025 (PT-88219).',
  },
  {
    id: 'log-003',
    timestamp: '2026-10-03T08:22:10Z',
    staffId: 'PH-1025',
    staffName: 'Sagar Patel',
    role: 'PHARMACIST',
    action: 'VERIFICATION_PASSED',
    entityType: 'VERIFICATION',
    entityId: 'pm-101',
    details: 'Barcode 8901112223334 matched Paracetamol 500 mg Tablet. ESP32 Green Strobe triggered.',
  },
  {
    id: 'log-004',
    timestamp: '2026-10-03T08:24:45Z',
    staffId: 'PH-1025',
    staffName: 'Sagar Patel',
    role: 'PHARMACIST',
    action: 'VERIFICATION_PASSED',
    entityType: 'VERIFICATION',
    entityId: 'pm-102',
    details: 'Barcode 8902223334441 matched Amoxicillin 500 mg Capsule. ESP32 Green Strobe triggered.',
  },
];

export const INITIAL_ACTIVE_SESSIONS: ActiveSession[] = [
  {
    id: 'sess-01',
    device: 'Hospital Handheld Terminal (Honeywell CT40)',
    platform: 'Android',
    browser: 'Chrome Mobile WebView 128.0',
    ipAddress: '10.14.22.84 (Ward 3 AP)',
    lastActive: 'Active now',
    isCurrent: true,
  },
  {
    id: 'sess-02',
    device: 'Central Pharmacy Workstation 02',
    platform: 'Terminal',
    browser: 'ChromeOS Clinical Client',
    ipAddress: '10.14.10.15 (Central Switch)',
    lastActive: '2 hours ago',
    isCurrent: false,
  },
  {
    id: 'sess-03',
    device: 'Clinical Review Tablet (iPadOS)',
    platform: 'Web',
    browser: 'Safari Mobile 18.1',
    ipAddress: '10.14.20.102 (Clinical VLAN)',
    lastActive: 'Yesterday at 17:42',
    isCurrent: false,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    title: 'New Override Request',
    message: 'Pharmacist Rahul requested clinical override for Pantoprazole 40 mg (Rx #1024).',
    type: 'OVERRIDE_REQUEST',
    timestamp: '5 min ago',
    isRead: false,
    targetRole: 'SUPERVISOR',
    relatedId: 'req-01',
  },
  {
    id: 'notif-02',
    title: 'Prescription Ready for Verification',
    message: 'Prescription #1025 confirmed by Sagar Patel. 1 pending item remaining.',
    type: 'REVIEW_REQUIRED',
    timestamp: '20 min ago',
    isRead: false,
    targetRole: 'PHARMACIST',
    relatedId: 'rx-1025',
  },
  {
    id: 'notif-03',
    title: 'Security Policy Active',
    message: 'Session inactivity timeout is set to 5 minutes to comply with hospital policy.',
    type: 'SECURITY',
    timestamp: '1 hour ago',
    isRead: true,
  },
  {
    id: 'notif-04',
    title: 'Verification Completed',
    message: 'Dispensing verification for Prescription #1024 completed by Rahul Sharma.',
    type: 'VERIFICATION_COMPLETE',
    timestamp: '1 hour ago',
    isRead: true,
  },
];

export const INITIAL_OVERRIDE_REQUESTS: OverrideRequest[] = [
  {
    id: 'req-01',
    prescriptionId: 'rx-1025',
    prescriptionNumber: '1025',
    medicineId: 'pm-103',
    medicineName: 'Pantoprazole',
    expectedStrength: '40 mg',
    expectedForm: 'Tablet',
    scannedMedicineName: 'Pantoprazole Sodium (Pan 40)',
    scannedStrength: '40 mg',
    scannedForm: 'Tablet',
    pharmacistId: 'PH-1025',
    pharmacistName: 'Sagar Patel',
    pharmacistNote: 'Manufacturer pack brand substitution (Pan 40 by Alkem) approved per hospital formulary equivalent listing.',
    requestedAt: '2026-10-03T08:26:00Z',
    status: 'PENDING',
  },
];

export const INITIAL_TEAM_MEMBERS: TeamMemberStats[] = [
  {
    staffId: 'PH-1025',
    name: 'Sagar Patel',
    role: 'PHARMACIST',
    department: 'Central Inpatient Pharmacy',
    todayVerifications: 14,
    mismatchesDetected: 1,
    status: 'ACTIVE',
    lastActiveTime: 'Active now',
  },
  {
    staffId: 'PH-1040',
    name: 'Rahul Sharma',
    role: 'PHARMACIST',
    department: 'Outpatient Dispensing Wing',
    todayVerifications: 18,
    mismatchesDetected: 2,
    status: 'ACTIVE',
    lastActiveTime: '12 min ago',
  },
  {
    staffId: 'SUP-112',
    name: 'Priya Shah',
    role: 'SUPERVISOR',
    department: 'Quality & Clinical Safety',
    todayVerifications: 6,
    mismatchesDetected: 0,
    status: 'ACTIVE',
    lastActiveTime: '25 min ago',
  },
];

export interface SamplePrescriptionPreset {
  id: string;
  title: string;
  doctor: string;
  patient: string;
  medicines: Array<{
    medicineName: string;
    strength: string;
    dosageForm: string;
    dose: string;
    frequency: string;
    route: string;
    duration: string;
    quantity: number;
  }>;
}

export const SAMPLE_PRESCRIPTIONS_DATA: SamplePrescriptionPreset[] = [
  {
    id: 'sample-standard-5',
    title: 'Ward 3 Standard Regimen (5 Medications)',
    doctor: 'Dr. Robert Chen, MD',
    patient: 'PT-88219 (Bed 302-B, Ward 3)',
    medicines: [
      {
        medicineName: 'Paracetamol',
        strength: '500 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet (500mg)',
        frequency: 'TID (Every 8 hours)',
        route: 'Oral',
        duration: '3 days',
        quantity: 9,
      },
      {
        medicineName: 'Amoxicillin',
        strength: '500 mg',
        dosageForm: 'Capsule',
        dose: '1 capsule (500mg)',
        frequency: 'TID (Every 8 hours)',
        route: 'Oral',
        duration: '5 days',
        quantity: 15,
      },
      {
        medicineName: 'Pantoprazole',
        strength: '40 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet (40mg)',
        frequency: 'OD (Once daily before breakfast)',
        route: 'Oral',
        duration: '5 days',
        quantity: 5,
      },
      {
        medicineName: 'Metformin',
        strength: '500 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet (500mg)',
        frequency: 'BID (With meals)',
        route: 'Oral',
        duration: '30 days',
        quantity: 60,
      },
      {
        medicineName: 'Atorvastatin',
        strength: '20 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet (20mg)',
        frequency: 'QHS (At bedtime)',
        route: 'Oral',
        duration: '30 days',
        quantity: 30,
      },
    ],
  },
  {
    id: 'sample-cardio-post-op',
    title: 'Post-Op Cardiac & Thromboprophylaxis Regimen',
    doctor: 'Dr. Sarah Jenkins, MD',
    patient: 'PT-41092 (Cardiac Care Unit, Bed 4)',
    medicines: [
      {
        medicineName: 'Aspirin',
        strength: '75 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet (75mg)',
        frequency: 'OD (Once daily)',
        route: 'Oral',
        duration: '30 days',
        quantity: 30,
      },
      {
        medicineName: 'Atorvastatin',
        strength: '20 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet (20mg)',
        frequency: 'QHS (At bedtime)',
        route: 'Oral',
        duration: '30 days',
        quantity: 30,
      },
      {
        medicineName: 'Pantoprazole',
        strength: '40 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet (40mg)',
        frequency: 'OD (Morning)',
        route: 'Oral',
        duration: '14 days',
        quantity: 14,
      },
      {
        medicineName: 'Metoprolol',
        strength: '50 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet (50mg)',
        frequency: 'BID (Every 12 hours)',
        route: 'Oral',
        duration: '30 days',
        quantity: 60,
      },
    ],
  },
  {
    id: 'sample-resp-infection',
    title: 'Acute Respiratory Tract Regimen',
    doctor: 'Dr. Michael Chang, MD',
    patient: 'PT-66380 (Outpatient Ambulatory Clinic)',
    medicines: [
      {
        medicineName: 'Azithromycin',
        strength: '500 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet (500mg)',
        frequency: 'OD (Once daily)',
        route: 'Oral',
        duration: '3 days',
        quantity: 3,
      },
      {
        medicineName: 'Cetirizine',
        strength: '10 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet (10mg)',
        frequency: 'QHS (At night)',
        route: 'Oral',
        duration: '7 days',
        quantity: 7,
      },
      {
        medicineName: 'Paracetamol',
        strength: '650 mg',
        dosageForm: 'Tablet',
        dose: '1 tablet (650mg)',
        frequency: 'PRN (As needed for fever/pain)',
        route: 'Oral',
        duration: '5 days',
        quantity: 10,
      },
    ],
  },
];

